export async function GET() {
  const data = [
    {
      Rok: 2023,
      Kraj: "Praha",
      "Měrné emise": 24.45,
      Látka: "CO",
      Jednotka: "t",
      AQI: 77.41404089421539,
    },
    {
      Rok: 2023,
      Kraj: "Praha",
      "Měrné emise": 15.38,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Praha",
      "Měrné emise": 1.47,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Praha",
      "Měrné emise": 1.06,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Praha",
      "Měrné emise": 0.28,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Jihočeský kraj",
      "Měrné emise": 4.76,
      Látka: "CO",
      Jednotka: "t",
      AQI: 2.337550932875827,
    },
    {
      Rok: 2023,
      Kraj: "Jihočeský kraj",
      "Měrné emise": 0.92,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Jihočeský kraj",
      "Měrné emise": 0.43,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Jihočeský kraj",
      "Měrné emise": 0.35,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Jihočeský kraj",
      "Měrné emise": 0.19,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Jihomoravský kraj",
      "Měrné emise": 5.68,
      Látka: "CO",
      Jednotka: "t",
      AQI: 5.676438080469817,
    },
    {
      Rok: 2023,
      Kraj: "Jihomoravský kraj",
      "Měrné emise": 1.55,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Jihomoravský kraj",
      "Měrné emise": 0.54,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Jihomoravský kraj",
      "Měrné emise": 0.37,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Jihomoravský kraj",
      "Měrné emise": 0.12,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Karlovarský kraj",
      "Měrné emise": 4.15,
      Látka: "CO",
      Jednotka: "t",
      AQI: 0.0,
    },
    {
      Rok: 2023,
      Kraj: "Karlovarský kraj",
      "Měrné emise": 1.32,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Karlovarský kraj",
      "Měrné emise": 0.4,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Karlovarský kraj",
      "Měrné emise": 0.31,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Karlovarský kraj",
      "Měrné emise": 0.76,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Kraj Vysočina",
      "Měrné emise": 6.28,
      Látka: "CO",
      Jednotka: "t",
      AQI: 7.853973176726771,
    },
    {
      Rok: 2023,
      Kraj: "Kraj Vysočina",
      "Měrné emise": 1.29,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Kraj Vysočina",
      "Měrné emise": 0.56,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Kraj Vysočina",
      "Měrné emise": 0.44,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Kraj Vysočina",
      "Měrné emise": 0.17,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Královéhradecký kraj",
      "Měrné emise": 7.22,
      Látka: "CO",
      Jednotka: "t",
      AQI: 11.265444827529315,
    },
    {
      Rok: 2023,
      Kraj: "Královéhradecký kraj",
      "Měrné emise": 1.44,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Královéhradecký kraj",
      "Měrné emise": 0.69,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Královéhradecký kraj",
      "Měrné emise": 0.57,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Královéhradecký kraj",
      "Měrné emise": 0.46,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Liberecký kraj",
      "Měrné emise": 8.23,
      Látka: "CO",
      Jednotka: "t",
      AQI: 14.930962239561854,
    },
    {
      Rok: 2023,
      Kraj: "Liberecký kraj",
      "Měrné emise": 1.19,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Liberecký kraj",
      "Měrné emise": 0.69,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Liberecký kraj",
      "Měrné emise": 0.64,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Liberecký kraj",
      "Měrné emise": 0.33,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Moravskoslezský kraj",
      "Měrné emise": 32.67,
      Látka: "CO",
      Jednotka: "t",
      AQI: 100.0,
    },
    {
      Rok: 2023,
      Kraj: "Moravskoslezský kraj",
      "Měrné emise": 2.61,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Moravskoslezský kraj",
      "Měrné emise": 0.91,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Moravskoslezský kraj",
      "Měrné emise": 0.75,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Moravskoslezský kraj",
      "Měrné emise": 1.7,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Olomoucký kraj",
      "Měrné emise": 6.41,
      Látka: "CO",
      Jednotka: "t",
      AQI: 8.325772447582438,
    },
    {
      Rok: 2023,
      Kraj: "Olomoucký kraj",
      "Měrné emise": 1.32,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Olomoucký kraj",
      "Měrné emise": 0.55,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Olomoucký kraj",
      "Měrné emise": 0.44,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Olomoucký kraj",
      "Měrné emise": 0.35,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Pardubický kraj",
      "Měrné emise": 7.29,
      Látka: "CO",
      Jednotka: "t",
      AQI: 11.5194905887593,
    },
    {
      Rok: 2023,
      Kraj: "Pardubický kraj",
      "Měrné emise": 2.34,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Pardubický kraj",
      "Měrné emise": 0.71,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Pardubický kraj",
      "Měrné emise": 0.56,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Pardubický kraj",
      "Měrné emise": 0.94,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Plzeňský kraj",
      "Měrné emise": 4.62,
      Látka: "CO",
      Jednotka: "t",
      AQI: 1.8294594104158755,
    },
    {
      Rok: 2023,
      Kraj: "Plzeňský kraj",
      "Měrné emise": 0.97,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Plzeňský kraj",
      "Měrné emise": 0.45,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Plzeňský kraj",
      "Měrné emise": 0.35,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Plzeňský kraj",
      "Měrné emise": 0.29,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Středočeský kraj",
      "Měrné emise": 7.79,
      Látka: "CO",
      Jednotka: "t",
      AQI: 13.334103168973424,
    },
    {
      Rok: 2023,
      Kraj: "Středočeský kraj",
      "Měrné emise": 1.74,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Středočeský kraj",
      "Měrné emise": 0.74,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Středočeský kraj",
      "Měrné emise": 0.59,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Středočeský kraj",
      "Měrné emise": 0.62,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Ústecký kraj",
      "Měrné emise": 7.51,
      Látka: "CO",
      Jednotka: "t",
      AQI: 12.31792012405351,
    },
    {
      Rok: 2023,
      Kraj: "Ústecký kraj",
      "Měrné emise": 4.21,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Ústecký kraj",
      "Měrné emise": 0.8,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Ústecký kraj",
      "Měrné emise": 0.52,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Ústecký kraj",
      "Měrné emise": 2.2,
      Látka: "SO₂",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Zlínský kraj",
      "Měrné emise": 7.56,
      Látka: "CO",
      Jednotka: "t",
      AQI: 12.499381382074922,
    },
    {
      Rok: 2023,
      Kraj: "Zlínský kraj",
      "Měrné emise": 1.5,
      Látka: "NOₓ",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Zlínský kraj",
      "Měrné emise": 0.58,
      Látka: "PM₁₀",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Zlínský kraj",
      "Měrné emise": 0.49,
      Látka: "PM₂,₅",
      Jednotka: "t",
    },
    {
      Rok: 2023,
      Kraj: "Zlínský kraj",
      "Měrné emise": 0.57,
      Látka: "SO₂",
      Jednotka: "t",
    },
  ];

  return Response.json({ data });
}
